version: '3.8'

services:
  app:
    container_name: mixa-lab-app
    build:
      context: .
      target: runner
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      # Sobreescribimos la URL de la base de datos para conectar al servicio 'db'
      DATABASE_URL: mysql://root:${DATABASE_PASSWORD:-12345678}@db:3306/mixalab
      PORT: 3001
      HOSTNAME: "0.0.0.0"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    container_name: mixa-lab-migrate
    build:
      context: .
      target: builder
    # Ejecutamos las migraciones para crear las tablas
    command: npx prisma migrate deploy
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://root:${DATABASE_PASSWORD:-12345678}@db:3306/mixalab
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mixa-lab-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-12345678}
      MYSQL_DATABASE: mixalab
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
  db_data:
