version: '3.8'

services:
  app:
    container_name: mixa-lab-app
    build:
      context: .
      dockerfile: Dockerfile
      # Usamos el target 'runner' definido en tu Dockerfile para producción
      target: runner
    command: /bin/sh -c "npx prisma migrate deploy && node server.mjs"
    restart: always
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - .env
    environment:
      - PORT=3001
      - HOSTNAME=0.0.0.0
      # Variables públicas necesarias
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3001/api}
